apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.prod }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.prod }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Values.global.prod }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.prod }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.prod }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.global.prod }}
  apiGroup: rbac.authorization.k8s.io
