// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using IstioOperatorSpec within kubernetes types, where deepcopy-gen is used.
func (in *IstioOperatorSpec) DeepCopyInto(out *IstioOperatorSpec) {
	p := proto.Clone(in).(*IstioOperatorSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioOperatorSpec. Required by controller-gen.
func (in *IstioOperatorSpec) DeepCopy() *IstioOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(IstioOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioOperatorSpec. Required by controller-gen.
func (in *IstioOperatorSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using InstallStatus within kubernetes types, where deepcopy-gen is used.
func (in *InstallStatus) DeepCopyInto(out *InstallStatus) {
	p := proto.Clone(in).(*InstallStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallStatus. Required by controller-gen.
func (in *InstallStatus) DeepCopy() *InstallStatus {
	if in == nil {
		return nil
	}
	out := new(InstallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new InstallStatus. Required by controller-gen.
func (in *InstallStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using InstallStatus_VersionStatus within kubernetes types, where deepcopy-gen is used.
func (in *InstallStatus_VersionStatus) DeepCopyInto(out *InstallStatus_VersionStatus) {
	p := proto.Clone(in).(*InstallStatus_VersionStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallStatus_VersionStatus. Required by controller-gen.
func (in *InstallStatus_VersionStatus) DeepCopy() *InstallStatus_VersionStatus {
	if in == nil {
		return nil
	}
	out := new(InstallStatus_VersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new InstallStatus_VersionStatus. Required by controller-gen.
func (in *InstallStatus_VersionStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
