/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "pluma.io/api/istio/v1alpha1"
)

// FakeIstioOperators implements IstioOperatorInterface
type FakeIstioOperators struct {
	Fake *FakeIstioV1alpha1
	ns   string
}

var istiooperatorsResource = schema.GroupVersionResource{Group: "install.istio.io", Version: "v1alpha1", Resource: "istiooperators"}

var istiooperatorsKind = schema.GroupVersionKind{Group: "install.istio.io", Version: "v1alpha1", Kind: "IstioOperator"}

// Get takes name of the istioOperator, and returns the corresponding istioOperator object, and an error if there is any.
func (c *FakeIstioOperators) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IstioOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(istiooperatorsResource, c.ns, name), &v1alpha1.IstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioOperator), err
}

// List takes label and field selectors, and returns the list of IstioOperators that match those selectors.
func (c *FakeIstioOperators) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IstioOperatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(istiooperatorsResource, istiooperatorsKind, c.ns, opts), &v1alpha1.IstioOperatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IstioOperatorList{ListMeta: obj.(*v1alpha1.IstioOperatorList).ListMeta}
	for _, item := range obj.(*v1alpha1.IstioOperatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested istioOperators.
func (c *FakeIstioOperators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(istiooperatorsResource, c.ns, opts))

}

// Create takes the representation of a istioOperator and creates it.  Returns the server's representation of the istioOperator, and an error, if there is any.
func (c *FakeIstioOperators) Create(ctx context.Context, istioOperator *v1alpha1.IstioOperator, opts v1.CreateOptions) (result *v1alpha1.IstioOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(istiooperatorsResource, c.ns, istioOperator), &v1alpha1.IstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioOperator), err
}

// Update takes the representation of a istioOperator and updates it. Returns the server's representation of the istioOperator, and an error, if there is any.
func (c *FakeIstioOperators) Update(ctx context.Context, istioOperator *v1alpha1.IstioOperator, opts v1.UpdateOptions) (result *v1alpha1.IstioOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(istiooperatorsResource, c.ns, istioOperator), &v1alpha1.IstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioOperator), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIstioOperators) UpdateStatus(ctx context.Context, istioOperator *v1alpha1.IstioOperator, opts v1.UpdateOptions) (*v1alpha1.IstioOperator, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(istiooperatorsResource, "status", c.ns, istioOperator), &v1alpha1.IstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioOperator), err
}

// Delete takes name of the istioOperator and deletes it. Returns an error if one occurs.
func (c *FakeIstioOperators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(istiooperatorsResource, c.ns, name, opts), &v1alpha1.IstioOperator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIstioOperators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(istiooperatorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IstioOperatorList{})
	return err
}

// Patch applies the patch and returns the patched istioOperator.
func (c *FakeIstioOperators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IstioOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(istiooperatorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IstioOperator), err
}
